### PR TITLE
Validate data-derived timestamps at the adapter boundary

### LINKED ISSUE #1047: Backend: validate data-derived values at the adapter boundary (timestamps as the service clock)
## Summary

A second, smaller cluster from the audits — distinct from the dashboard push/pull program in #1046, but with the same shape of fix: several backend findings share the root cause that **adapters pass data-derived values across the trust boundary unvalidated, and each consumer guards (or doesn't) ad hoc**. The most dangerous instance is timestamps: the batcher uses data-derived timestamps as its *only* clock, with no sanity bound.

## Findings that trace to this root cause

- **#1038 finding 1 (High, reproduced):** a single far-future timestamp in the first consumed batch permanently wedges `SimpleMessageBatcher` (and the production `AdaptiveMessageBatcher`) — no batch is ever emitted again, messages pile up unbounded, and restarting re-consumes the same offset and wedges again. All four wire schemas (ev44, f144, da00, ad00) feed unvalidated data-derived timestamps into the batcher. The lag machinery *detects* future payloads and logs at ERROR, but nothing drops or clamps them.
- **#1038 finding 2 (Medium):** ev44 flatbuffers with absent event vectors return scalar `0` from the accessors, causing an `AttributeError` deep in the adapter — the message is silently dropped instead of hitting the intended timestamp fallback. An explicit empty-vector check at the boundary would recover these.
- **#1037 finding 4 (Medium):** multi-pulse ev44 on the monitor path is silently mis-stamped (all events get `reference_time[-1]`), while the detector path raises `NotImplementedError` for the same input. The two paths should agree, and the boundary is the place to enforce the invariant once.

## Proposed fix

One validation/normalization layer at the adapter boundary (where raw flatbuffers become domain messages), instead of per-consumer guards:

- **Bound data-derived timestamps against wall clock**: reject (or clamp, with a counter/log) payload timestamps more than N seconds in the future; optionally fall back to the Kafka broker `CreateTime` the adapters already read for lag reporting. This protects the batcher, the job scheduler, and run-reset logic at once.
- **Structural checks per schema**: empty/absent event vectors (ev44), `reference_time_index` consistency (multi-pulse), so malformed-but-recoverable messages are handled deliberately rather than via `except Exception` drops.
- Surface rejects/clamps in the existing stream stats so persistent upstream corruption is visible rather than silent.

## Why this is high value beyond the current findings

The boundary layer defends against *producers that don't exist yet*. Any future upstream component (new file writer version, new fake, a misconfigured beamline ingestor) that emits a bad timestamp today takes down the whole service via the batcher; with a boundary guard it costs one logged, counted, dropped message. This is the backend counterpart of the "safe by construction" argument in #1046.

Refs: #1038, #1037.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
## Why

The batcher hardening keeps services alive against pathological timestamps, but it cannot resolve every case: a lone far-future timestamp in the startup backlog is indistinguishable from real traffic without arrival-time evidence, and the simple batcher wedges on it (the strict xfail from #1122). The adapter boundary has that evidence — it sees the broker `CreateTime` and the consuming host's wall clock — so validation belongs there.

## What changed

Data-derived envelope timestamps implausibly far ahead of the wall clock (bound: 30 s; NTP skew is milliseconds, a broken clock is hours out, and three days of production logs contain no future-dated payload at all) are clamped at the adapter boundary. The clamp target is the broker `CreateTime` when itself plausible, the consumer's wall clock as a last resort — the order matters when consuming a backlog, where a wall-clock substitute would be a future outlier relative to the surrounding traffic and re-poison the batchers from within the bound.

The change establishes an explicit contract: **the envelope timestamp is livedata's transport clock** (batching, scheduling, run resets) and may be clamped freely, while **payload times are the device's claim** and reach science consumers unmodified. A wrong device clock stays visible and attributable in the data instead of being silently replaced by an estimate; consumers must tolerate wrong device times regardless, since a clock running behind passes any future bound. Concretely:

- No payload is rewritten on clamp, including f144.
- `event_time_zero` is now built from the payload's `reference_time` (threaded through the `Events` dataclasses) instead of inheriting the envelope, closing the path by which the clamp used to rewrite pulse times covertly. The envelope stands in only for messages carrying no pulse time.
- pl72/6s4t run start/stop times are the exception that proves the rule: they are control flow (they schedule job resets that fire when data time reaches them, so a far-future value would park a reset that never fires and lose the run transition) and are bounded like the envelope.

Clamping rather than dropping keeps data flowing during commissioning, when devices with broken clocks are expected. For a clamped ev44 stream this is a degraded mode with a known taxonomy: physics based on `event_time_offset` (most live reduction) is unaffected; correlation with slow f144 metadata holds at arrival-time accuracy while consumption is live; pulse-precision correlation is unrecoverable — no timestamp policy can restore it once the producer clock is broken.

Clamps are counted per stream and surfaced in the backend stream stats at warning severity, with a clamped-message column in the backend status widget. Adapters without a `StreamCounter` (dashboard-side routes) log once per stream instead of once per message.

While in the adapter, ev44 payloads whose event vectors are absent rather than empty now reach the broker-timestamp fallback intended for them, instead of dying on an `AttributeError` and being dropped (#1038 finding 2).

## Notes for review

An unmapped stream sending far-future timestamps is reported as unmapped rather than as a clamp: Kafka subscription is per-topic, and a foreign producer's broken clock should not raise warnings in a service that ignores its data.

A known residual hole: a message whose payload timestamp and `CreateTime` are both insane, consumed mid-backlog, degrades to the wall-clock fallback and is then a future outlier relative to the backlog's epoch; the rate-aware batcher recovers via re-anchoring, the simple batcher stays silent until catch-up completes.

A possible follow-up, deliberately not in scope: estimating a per-stream clock offset and clamping to `timestamp - offset`, which would preserve the pulse grid and upgrade coarse correlation to near-exact for constant-offset clocks.

Closes #1047. Also resolves findings 1 and 2 of #1038.

## Test plan

The strict xfail acceptance tests from #1053 and from #1122 now pass and their markers are removed. The far-future liveness tests exercise both clamp targets end-to-end. Adapter-level tests assert delivery with the clamped envelope, untouched payloads, the broker-time-vs-wall-clock cascade, run-time bounding, and once-per-stream warning rate-limiting without a counter.

- [ ] Backend status widget: confirm the clamped-message column and its summary badge render sensibly for a stream with clamps.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Closing in favour of #1141, which fixes what is left of this after #1122 landed in its final shape.

Re-checking the motivation against `main`:

- **Liveness no longer needs it.** The wall-clock backstop bounds a poisoned window at roughly ten batch lengths and costs one stall per poison message, and the rate-aware batcher is now the default. The remaining hole is specific to `SimpleMessageBatcher`, which is opt-in and slated for removal.
- **The data-clock damage this was sized against is currently unreachable.** `_fire_pending_resets` only ever sees an empty list, because `with_run_control_route` is a no-op for #795, and no `JobSchedule` carrying an `end_time` is constructed anywhere in `src/`. Both arm again later, but neither is live today — which also means the pl72/6s4t bounding commit here guards a disabled path with a 30 s bound that would clamp a legitimately scheduled future stop time.
- **The dashboard-side clamp cannot do anything.** `MessagePump` forwards only `stream` and `value`; the envelope timestamp is discarded. That takes the counter-less rate-limiting commit with it, which existed only to quiet warnings from a clamp with no effect.
- **The clamp would blind the detector we already have.** `_clamp_future` runs before `_record_lag`, so when the clamp target is the broker timestamp the recorded lag becomes exactly 0 — a stream that today logs `stream_lag` at ERROR drops to INFO. That is the measurement #1133 wants to build creep detection on.

What did survive is a permanent, in-band defect: a batch built from a lone far-future message anchors on it, and `Job._start_time` then latches a start time outside the stream's timeline for the job's lifetime, leaving every later result with `start_time > end_time`. #1141 corrects that where the evidence is (a job cannot begin after its accumulation ends) without a wall clock or a new layer.

The parts of this PR that stand on their own are separable and unaffected: per-source clock-offset telemetry belongs with #1133 and should extend the existing lag reporting rather than add a parallel counter; the ev44 absent-event-vector handling is #1124, closed separately.
